In [2]:
 1. Define a string variable with_ your name. Print characters of odd and_ even position of your name.


SyntaxError: invalid syntax (<ipython-input-2-60f4e8026fb4>, line 1)

In [3]:
name = "JackGuan"

In [4]:
print("---------------")
print(name[0::2])
print("---------------")
print(name[1::2])

---------------
JcGa
---------------
akun


In [5]:
for x in range(len(name)):
    if x % 2 == 0:
        print(name[x])

for y in range(len(name)):
    if y % 2 != 0:
        print(name[y])
    

J
c
G
a
a
k
u
n


In [11]:
2.Create three variables named 'Student name', 'Course name', and 'EmailAddress'. Add 5 random values in these variables, where added values are not replaceable, and print them.

SyntaxError: invalid syntax (<ipython-input-11-f24c325046e6>, line 1)

In [7]:
import random

In [31]:
student_name = ()
course_name = ()
email_address = ()

for x in range(5):
    student_name += ("Student_" + str(random.randint(1,100 )),)
    course_name += ("Course_" + str(random.randint(1, 10)),)
    email_address += ("student" + str(random.randint(1, 10)) + "@1.com",)

print("Student Names:", student_name)
print("Course Names:", course_name)
print("Email Addresses:", email_address)

print(type(student_name))


Student Names: ('Student_1', 'Student_75', 'Student_12', 'Student_20', 'Student_94')
Course Names: ('Course_10', 'Course_2', 'Course_2', 'Course_1', 'Course_3')
Email Addresses: ('student3@1.com', 'student1@1.com', 'student5@1.com', 'student2@1.com', 'student5@1.com')
<class 'tuple'>


In [9]:
3. Create a dictionary variable with three keys, which are named same as the three variables created in the previous problem. Insert the previously created three variables values in the dictionary variable and print it.

SyntaxError: invalid syntax (<ipython-input-9-c374d13560b4>, line 1)

In [32]:
dict = {}

dict['Student name'] = student_name
dict['Course name'] = course_name
dict['EmailAddress'] = email_address

print(dict)
print(type(dict))
print(type(student_name))

{'Student name': ('Student_1', 'Student_75', 'Student_12', 'Student_20', 'Student_94'), 'Course name': ('Course_10', 'Course_2', 'Course_2', 'Course_1', 'Course_3'), 'EmailAddress': ('student3@1.com', 'student1@1.com', 'student5@1.com', 'student2@1.com', 'student5@1.com')}
<class 'dict'>
<class 'tuple'>


In [ ]:
4.Define a string variable 'energy' and assign value either 'Fossil' or 'Renewable'. Print "Natural gas" if the value of energy variable is 'Fossil' otherwise print "solar power". What will your program print if energy='Biomass '?

In [18]:
energy = 'Fossil'

if energy == 'Fossil':
    print("Natural gas")
else:
    print("solar power")
    
print("if energy = Biomass, the program will not print any because there are no condition for that , even it's same meaning")

Natural gas
if energy = Biomass, the program will not print any because there are no condition for that , even it's same meaning


In [ ]:
5.Print all prime numbers between 0 and 100 separated by line.5.

In [22]:
for x in range(2,101):
    for y in range(2,101):
        if x % y == 0:
            break
    if x == y:
        print(x, end = ",")

2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,

In [ ]:
()6.Is it possible to break a loop before executing for the defined number of iterations? If yes, provide an example using While loop structure. Otherwise, explain your answer (why and how).

In [25]:
a = 1

while True:
    print("testing",a)
    a += 1
    
    if a == 3:
        break

testing 1
testing 2


In [ ]:
7.Create  functions named  'Addition', 'Multiplication', 'Division' and 'Subtraction'. These functions takes two input parameters say (x, y) and return (x+y),(x*y), (x/y) and (x-y). Call the function with (4,7) arguments and print the outputs

In [26]:
def Addition(x, y):
    return x + y

def Multiplication(x, y):
    return x * y

def Division(x, y):
    if y != 0:
        return x / y
    else:
        raise ValueError("Division by zero is not allowed.")

def Subtraction(x, y):
    return x - y

x = 4
y = 7

print("Addition:", Addition(x, y))
print("Multiplication:", Multiplication(x, y))
print("Division:", Division(x, y))
print("Subtraction:", Subtraction(x, y))

Addition: 11
Multiplication: 28
Division: 0.5714285714285714
Subtraction: -3


In [ ]:
8.Create and display a 8x8 Identity matrix and multiply it with a 8x4 Random matrix.

In [35]:
import numpy as np

In [36]:
x = np.zeros((8,8),dtype = int)
print(x)

y = np.random.rand(8,4)
print(y)

print(np.dot(x, y))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0.07756861 0.16171158 0.47202029 0.46505266]
 [0.61010209 0.73019616 0.53977515 0.60752854]
 [0.78825041 0.50490946 0.9258402  0.22890639]
 [0.78144228 0.20678514 0.68423985 0.08425472]
 [0.29077879 0.35057113 0.38087315 0.7764529 ]
 [0.9229707  0.78526362 0.51901167 0.40001265]
 [0.95370238 0.92669531 0.75250705 0.89193508]
 [0.23818216 0.71816214 0.20333704 0.20785159]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
9.Create a 8x9 matrix, initialise with random values and print it. Now, transpose the matrix and print it. How the transposed matrix is different from original matrix?

Object `matrix` not found.


In [ ]:
9.Create a 8x9 matrix, initialise with random values and print it. Now, transpose the matrix and print it. How the transposed matrix is different from original matrix

In [41]:
x = np.random.rand(8, 9)
print(x)
print("--------------------------------------------")

transposed_matrix = np.transpose(x)

print(transposed_matrix)

[[0.59882835 0.08912866 0.57701321 0.72450256 0.31600071 0.03699442
  0.8142279  0.44577505 0.76196176]
 [0.11684989 0.52742283 0.58072965 0.85886494 0.87257248 0.33628151
  0.17635662 0.85360976 0.19231127]
 [0.01677829 0.80550524 0.64325278 0.57775398 0.38169541 0.95484339
  0.20281401 0.11414599 0.38427546]
 [0.24407335 0.69951169 0.3379791  0.93171836 0.90367478 0.07086498
  0.23715568 0.64874169 0.7507562 ]
 [0.70992469 0.49292051 0.14560701 0.69889961 0.32000015 0.83381955
  0.05294844 0.03876648 0.77063412]
 [0.78332256 0.41094174 0.43643019 0.57049472 0.97790563 0.58207032
  0.06414961 0.92139266 0.50808193]
 [0.85401697 0.1661745  0.85077285 0.72156966 0.9557161  0.77566575
  0.12184896 0.13556113 0.33859703]
 [0.4541185  0.96145952 0.94800747 0.34350331 0.25369713 0.12793444
  0.96381006 0.01985119 0.44143859]]
--------------------------------------------
[[0.59882835 0.11684989 0.01677829 0.24407335 0.70992469 0.78332256
  0.85401697 0.4541185 ]
 [0.08912866 0.52742283 0.805

In [ ]:
10.Expport the "PedestrianCounting.csv" file as a matrix. The row of the matrix represents data point or instance and the column represents the variable or feature. Print the number of data instances and variables present in this dataset. Calculate mean of the third variable and deduct this mean from original values of the variable. Print both original and modified values of the variable.

In [58]:
import pandas as pd

In [59]:
data = pd.read_json('2.json')
data_matrix = data.values

print("testing")
print(data_matrix)

testing
[['2023-07-04T11:00:00+10:00' 1 791 653 1444]
 ['2023-07-04T14:00:00+10:00' 1 1301 1074 2375]
 ['2023-07-04T17:00:00+10:00' 1 1532 931 2463]
 ...
 ['2023-07-27T12:00:00+10:00' 122 45 33 78]
 ['2023-07-27T19:00:00+10:00' 122 44 30 74]
 ['2023-07-27T20:00:00+10:00' 122 21 12 33]]


In [60]:
num_instances, num_variables = data.shape
print("Number of data instances:", num_instances)
print("Number of variables:", num_variables)

Number of data instances: 178827
Number of variables: 5


In [67]:
Direction_1 = data.iloc[:, 2]
mean_Direction_1 = Direction_1.mean()
Final_Direction_1 = Direction_1 - mean_Direction_1

In [68]:
print("Number of data instances:", num_instances)
print("Number of variables:", num_variables)
print("Mean of the Direction_1:", mean_Direction_1)
print("Values of the Direction_1 variable:")
print(Direction_1)
print("Final values of Direction_1 variable:")
print(Final_Direction_1)

Number of data instances: 178827
Number of variables: 5
Mean of the third variable: 208.55983156905836
Values of the Direction_1 variable:
0          791
1         1301
2         1532
3          527
4           85
          ... 
178822      39
178823      17
178824      45
178825      44
178826      21
Name: direction_1, Length: 178827, dtype: int64
Final values of Direction_1 variable:
0          582.440168
1         1092.440168
2         1323.440168
3          318.440168
4         -123.559832
             ...     
178822    -169.559832
178823    -191.559832
178824    -163.559832
178825    -164.559832
178826    -187.559832
Name: direction_1, Length: 178827, dtype: float64
